application: scorethai
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /s
  static_dir: s

- url: /(m/?)?(feed|_o)?
  script: main.py

- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin
  secure: always

derived_file_type:
- python_precompiled
